# TSV with list of paired-end fastq files

input_file: "/hps/nobackup2/production/metagenomics/aalmeida/project_latinbiota/amr_profiles/fastqs.tsv"
output_dir: "/hps/nobackup2/production/metagenomics/aalmeida/project_latinbiota/amr_profiles"
ncores: 4
